# Generated by Django 3.1.7 on 2021-03-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('age', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='mapping',
            name='cid',
        ),
        migrations.RemoveField(
            model_name='mapping',
            name='uid',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='uid',
            new_name='uname',
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Captain',
        ),
        migrations.DeleteModel(
            name='Mapping',
        ),
    ]
