# Generated by Django 3.1.7 on 2021-03-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_auto_20210307_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='vehicle_no',
            field=models.CharField(default='0000', max_length=10),
            preserve_default=False,
        ),
    ]
